### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by aa2727** [VendenIX/curriculum_vitae#1]
Bonjour, 
Je viens de lire votre CV et je constate qu'il y a une possible et éventuelle faute d'orthographe.
Il y est noté : " avec facilitée ".
Après vérification sur le larousse accessible à l'URL : https://www.larousse.fr/dictionnaires/francais/facilit%C3%A9/32585
Je crois qu'on écrit "facilité".

**Comment by VendenIX** [comment]
Merci Antoine
